#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set fstab.@global[0].anon_mount=1
uci commit fstab

rm -f /www/luci-static/resources/view/status/include/50_dsl.js
rm -f /www/luci-static/resources/view/status/include/70_ddns.js
rm -f /www/luci-static/resources/view/status/include/80_minidlna.js
rm -f /www/luci-static/resources/view/status/include/80_upnp.js

ln -sf /sbin/ip /usr/bin/ip

sed -i "s/# //g" /etc/opkg/distfeeds.conf

sed -i 's/root::0:0:99999:7:::/root:$1$/atvK01U$d72aizejNWUr9e3K2Qpc/0:19007:0:99999:7:::/g' /etc/shadow
[ -f '/bin/bash' ] && sed -i 's|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g' /etc/passwd

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

sed -i 's/[Ii]mmortal[Ww]rt/OpenWrt/g' /etc/openwrt_release
sed -i 's/[Ii]mmortal[Ww]rt/OpenWrt/g' /usr/lib/os-release
sed -i 's/[Ii]mmortal[Ww]rt/OpenWrt/g' /etc/device_info
sed -i 's/[Ii]mmortal[Ww]rt/OpenWrt/g' /etc/openwrt_banner
sed -i 's/[Ii]mmortal[Ww]rt/OpenWrt/g' /etc/config/luci


exit 0
